root: true
parser: "@typescript-eslint/parser"
plugins: ["@typescript-eslint"]
env:
  browser: false
  es2017: true
  node: true
extends:
  - google
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
parserOptions:
  ecmaVersion: 8
  sourceType: module
rules: {
  linebreak-style: off
}